src/main/java/lt/vtvpmc/exam/entities/Client.java
package lt.vtvpmc.exam.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;


@Entity
public class Client implements Serializable {
    
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;
    
    @NotNull
    private String firstName;
    
    @NotNull
    private String lastName;
    
    @NotNull
    private String phoneNumber;
    
    @NotNull
    @Temporal(TemporalType.DATE)
    private Date dateOfBirth;
    
    @NotNull
    @Enumerated(EnumType.ORDINAL)
    private ClientType type;
    
	@OneToMany(mappedBy="client", orphanRemoval=true, fetch=FetchType.EAGER, cascade=CascadeType.REMOVE)
    private List<Item> items;

    public Client() {
    }

    public Client(String firstName, String lastName, String phoneNumber, Date dateOfBirth, ClientType type) {
		super();
		this.firstName = firstName;
		this.lastName = lastName;
		this.phoneNumber = phoneNumber;
		this.dateOfBirth = dateOfBirth;
		this.type = type;
	}
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public ClientType getType() {
		return type;
	}

	public void setType(ClientType type) {
		this.type = type;
	}

	public List<Item> getItems() {
		return items;
	}

	public void setItems(List<Item> items) {
		this.items = items;
	}
    
    
    
}

src/main/java/lt/vtvpmc/exam/entities/ClientType.java
package lt.vtvpmc.exam.entities;

public enum ClientType {
	SIMPLE("Simple"),
	LOYAL("Loyal");
	
	private String value;
	
	private ClientType(String value){
		this.value = value;
	}
	
	public String getValue() {
		return value;
	}
}

src/main/java/lt/vtvpmc/exam/entities/Item.java
package lt.vtvpmc.exam.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

@Entity
public class Item implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;
    
    @NotNull
    private String name;
    
    @NotNull
    private Integer weight;
    
    @NotNull
    @Max(40)
    @Min(1)
    private Integer sector;
    
    @NotNull
    @Temporal(TemporalType.DATE)
    private Date date;

    @ManyToOne(fetch = FetchType.EAGER)
    private Client client;
    
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getWeight() {
		return weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	public Integer getSector() {
		return sector;
	}

	public void setSector(Integer sector) {
		this.sector = sector;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}
	
	
    
    
}

src/main/java/lt/vtvpmc/exam/ui/ClientListBean.java
package lt.vtvpmc.exam.ui;

import java.io.Serializable;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import javax.persistence.TypedQuery;

import org.springframework.transaction.annotation.Transactional;

import lt.vtvpmc.exam.entities.Client;
import lt.vtvpmc.exam.entities.Item;

/**
 *
 * @author giedrius
 */
public class ClientListBean implements Serializable {
    
    @PersistenceContext
    private EntityManager entityManager;
    
    private ClientModel clientModel;
    
    @Transactional(readOnly = true)
    public List<Client> getClientList() {
        Query q = entityManager.createQuery("select c from Client c");
        return q.getResultList();
    }
    
    @Transactional
    public void removeClient(Client client) {
        entityManager.remove(entityManager.merge(client));
    }
    
    public Integer getNumberOfInventory(Client client)
    {
		TypedQuery<Item> query = entityManager.createQuery("SELECT t From Item t WHERE t.client = :client", Item.class);
		query.setParameter("client", client);
		return query.getResultList().size();
    }
    
	public String overview(Client client) {
		clientModel.setCurrentClient(client);
		return "client";
	}

	public ClientModel getClientModel() {
		return clientModel;
	}

	public void setClientModel(ClientModel clientModel) {
		this.clientModel = clientModel;
	}
    
}

src/main/java/lt/vtvpmc/exam/ui/ItemController.java
package lt.vtvpmc.exam.ui;

import java.io.Serializable;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.springframework.transaction.annotation.Transactional;

import lt.vtvpmc.exam.entities.Item;

public class ItemController implements Serializable {
	
	private ItemModel itemModel;
	private ClientModel clientModel;
	
	@PersistenceContext
	private EntityManager em;

	@Transactional
	public String save() {
		if (!clientModel.getCurrentClient().getItems().contains(itemModel.getCurrentItem())) {
			clientModel.getCurrentClient().getItems().add(itemModel.getCurrentItem());
		}
		em.persist(itemModel.getCurrentItem());
		return "client";
	}

	@Transactional
	public String delete(Item item) {
		clientModel.getCurrentClient().getItems().remove(item);
		em.remove(em.merge(item));
		return "client";
	}
	
	public String create(){
		Item newItem = new Item();
		newItem.setClient(clientModel.getCurrentClient());
		itemModel.setCurrentItem(newItem);
		return "addItem";
	}
	
	public String cancel() {
		itemModel.setCurrentItem(null);
		return "client";
	}
	
	public ItemModel getItemModel() {
		return itemModel;
	}

	public void setItemModel(ItemModel itemModel) {
		this.itemModel = itemModel;
	}

	public ClientModel getClientModel() {
		return clientModel;
	}

	public void setClientModel(ClientModel clientModel) {
		this.clientModel = clientModel;
	}
}

src/main/java/lt/vtvpmc/exam/ui/NewClientBean.java
package lt.vtvpmc.exam.ui;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import org.springframework.transaction.annotation.Transactional;

import lt.vtvpmc.exam.entities.Client;
import lt.vtvpmc.exam.entities.ClientType;



public class NewClientBean implements Serializable {
    
    @PersistenceContext
    private EntityManager entityManager;
    
    private String clientFirstName;
    private String clientLastName;
    private String clientPhoneNumber;
    private Date dateOfBirth;
    private ClientType clientType;
    
    
    @Transactional
    public String save() {
    	if (getClientByNameAndDate(clientFirstName, clientLastName, dateOfBirth).size() == 0){
    		Client client = new Client(clientFirstName, clientLastName, clientPhoneNumber, dateOfBirth, clientType);
    		entityManager.persist(client);
    		return "main";
        } else {
        	return "error";
        }
    }
    
    @Transactional
    public List<Client> getClientByNameAndDate(String firstName, String lastName, Date dateOfBirth) {
        Query q = entityManager.createQuery("select c from Client c where c.firstName = :firstName and c.lastName = :lastName and c.dateOfBirth = :dateOfBirth");
        q.setParameter("firstName", firstName);
        q.setParameter("lastName", lastName);
        q.setParameter("dateOfBirth", dateOfBirth);
        return q.getResultList();
    }
    
    public String getClientFirstName() {
        return clientFirstName;
    }

    public void setClientFirstName(String clientFirstName) {
        this.clientFirstName = clientFirstName;
    }

    public String getClientLastName() {
        return clientLastName;
    }

    public void setClientLastName(String clientLastName) {
        this.clientLastName = clientLastName;
    }

    public String getClientPhoneNumber() {
        return clientPhoneNumber;
    }

    public void setClientPhoneNumber(String clientPhoneNumber) {
        this.clientPhoneNumber = clientPhoneNumber;
    }

	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public ClientType getClientType() {
		return clientType;
	}

	public void setClientType(ClientType clientType) {
		this.clientType = clientType;
	}
}

src/main/java/lt/vtvpmc/exam/ui/ReportBean.java
package lt.vtvpmc.exam.ui;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import org.springframework.transaction.annotation.Transactional;

import lt.vtvpmc.exam.entities.Client;
import lt.vtvpmc.exam.entities.Item;

public class ReportBean implements Serializable {

	private ClientListBean clientListBean;
	@PersistenceContext
	private EntityManager entityManager;

	public Integer getWeightSum(Client client) {
		int sum = 0;
		for (Item item: client.getItems()){
			sum += item.getWeight();
		}
		return sum;
	}
	
    @Transactional(readOnly = true)
    public List<Client> getClientListByItemCount() {
    	Query query = entityManager.createQuery("SELECT c From Client c order by size(c.items) DESC").setMaxResults(5);
    	return query.getResultList();
    }
    
    public List<Client> getClientListByWeigth()
    {
    	List<Client> filteredClients = new ArrayList<Client>();
    	List<Client> allClients = clientListBean.getClientList();
    	for (int i=0; i<5; i++){
    		if (i< allClients.size()){
    			filteredClients.add(allClients.get(i));
    		}
    	}
    	for (int j=0; j<allClients.size(); j++){
    		
    		for (int i=0; i<5; i++){
    			if (getWeightSum(allClients.get(j)) > getWeightSum(filteredClients.get(i))){
    		
    				if (!filteredClients.contains(allClients.get(j))){
        				filteredClients.set(i, allClients.get(j));
    				}
    				break;
    			}
    		}
    	}
    	return filteredClients;
    }
    


	public ClientListBean getClientListBean() {
		return clientListBean;
	}

	public void setClientListBean(ClientListBean clientListBean) {
		this.clientListBean = clientListBean;
	}
    
    

}

src/main/webapp/addItem.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets" template="template.xhtml">
    
	<ui:define name="page_title">
		Add new item
	</ui:define>
	<ui:define name="title">
		Add new item
	</ui:define>
    
    <ui:define name="content">
    
    <h:form>
    	<p:messages id="messages" showDetail="true" autoUpdate="true" />
    	
        <p:outputLabel for="name">Name: </p:outputLabel>
     	<p:inputText id="name" value="#{itemModel.currentItem.name}" required="true"
     	requiredMessage="Name cannot be empty"/>
     	
     	<p:outputLabel for="weight">Weight: </p:outputLabel>
     	<p:inputText id="weight" value="#{itemModel.currentItem.weight}" required="true"
     	requiredMessage="Weigth cannot be empty"/>
     	
     	<p:outputLabel for="sector">Sector: </p:outputLabel>
     	<p:inputText id="sector" value="#{itemModel.currentItem.sector}" required="true"
     	requiredMessage="Sector cannot be empty" validatorMessage="Sector must be between 1 and 40">
     		<f:validateLongRange maximum="40" minimum="1" for="sector"></f:validateLongRange>
     	</p:inputText>
     	
     	<p:outputLabel for="date">Date: </p:outputLabel>
     	<p:inputText id="date" value="#{itemModel.currentItem.date}" required="true"
     	requiredMessage="Date cannot be empty">
     		<f:convertDateTime type="date" pattern="yyyy-MM-dd" />
     	</p:inputText>
     	
     	<p:commandButton value="Save" action="#{itemController.save}" update="@form"/>
     	<p:commandButton value="Cancel" action="#{itemController.cancel}" immediate="true"/>
    </h:form>

    </ui:define>
    
</ui:composition>

src/main/webapp/addNewCustomer.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets" template="template.xhtml">
    
	<ui:define name="page_title">
		Add new client
	</ui:define>
	<ui:define name="title">
		Add new client
	</ui:define>
    
    <ui:define name="content">
        <h:form id="newCustomerForm">
        	
        	<p:messages id="messages" showDetail="true" autoUpdate="true" />
            
            <h:panelGrid columns="3">
                <h:outputText value="Name:"/>
                <h:inputText id="clientName" value="#{newClientBean.clientFirstName}" required="true"
						requiredMessage="Name cannot be empty"/>
                <h:message for="clientName"/>
                
                <h:outputText value="Surname:"/>
                <h:inputText id="clientSurname" value="#{newClientBean.clientLastName}" required="true"
                requiredMessage="Last name cannot be empty"/>
                <h:message for="clientSurname"/>
                
                <h:outputText value="Phone #:"/>
                <h:inputText id="clientPhoneNo" value="#{newClientBean.clientPhoneNumber}" required="true"
                requiredMessage="Phone number cannot be empty"/>
                <h:message for="clientPhoneNo"/>
                
                <h:outputText value="Date of birth:"/>
                <h:inputText id="birthDate" value="#{newClientBean.dateOfBirth}" required="true"
                requiredMessage="Date of birth cannot be empty">
                	<f:convertDateTime type="date" pattern="yyyy-MM-dd" />
                </h:inputText>
                <h:message for="birthDate"/>
                
                <p:selectOneButton id="type" value="#{newClientBean.clientType}" required="true"
                requiredMessage="Client type must be selected">
					<f:selectItem itemLabel="Simple" itemValue="SIMPLE" />
					<f:selectItem itemLabel="Loyal" itemValue="LOYAL" />
				</p:selectOneButton>
				<h:message for="type"/>
				
				
            </h:panelGrid>
            <h:commandButton action="#{newClientBean.save()}" value="Add"/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/client.xhtml
<!DOCTYPE html>
<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets" template="template.xhtml">
    
	<ui:define name="page_title">
		Client
	</ui:define>
	<ui:define name="title">
		Client
	</ui:define>
    
    <ui:define name="content">
    	<h:form>
			<p:dataTable class="table" value="#{clientModel.currentClient}" var="client">
				<f:facet name="header">
					Client
				</f:facet>
				<p:column headerText="First Name">
      				<h:outputText value="#{client.firstName}"/>
      			</p:column>
      			<p:column headerText="Last Name">
      				<h:outputText value="#{client.lastName}"/>
      			</p:column>
			</p:dataTable>
		</h:form>
		
		<br/>
		<br/>
		
		<h:form>
			<p:dataTable class="table" value="#{clientModel.currentClient.items}" var="item">
				<f:facet name="header">
					Items
				</f:facet>
				<f:facet name="header">
        			Invoice items
    			</f:facet>
      			<p:column headerText="Name">
      				<h:outputText value="#{item.name}"/>
      			</p:column>
      	    	<p:column headerText="Weight">
      				<h:outputText value="#{item.weight}"/>
      			</p:column>
      	    	<p:column headerText="Sector">
      				<h:outputText value="#{item.sector}"/>
      			</p:column>
      			<p:column headerText="Date">
      				<h:outputText value="#{item.date}"/>
      			</p:column>
      			<p:column headerText="Operations">
					<p:commandLink 
      					actionListener="#{itemController.delete(item)}" 
      					update="@form" value="Delete " immidiate="true">
					</p:commandLink>
      			</p:column>
			</p:dataTable>
			<p:commandLink action="#{itemController.create}" value="Add new item"/>
		</h:form>
    </ui:define>
    
</ui:composition>

src/main/webapp/error.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets" template="template.xhtml">
    
	<ui:define name="page_title">
		Warning
	</ui:define>
	
	<ui:define name="title">
		Warning
	</ui:define>
    
    <ui:define name="content">
    
    	There already is user with such name, last name and birth date.

    </ui:define>
    
</ui:composition>

src/main/webapp/main.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets" template="template.xhtml">

	<ui:define name="page_title">
		Client list
	</ui:define>
	<ui:define name="title">
		Client list
	</ui:define>
	
    <ui:define name="content">
        <h:form id="tableActionForm">
            <h:dataTable value="#{clientListBean.clientList}" var="client">
                <h:column>
                    <f:facet name="header">
                        First Name
                    </f:facet>
                    <h:outputText value="#{client.firstName}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Last Name
                    </f:facet>
                    <h:outputText value="#{client.lastName}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Phone number
                    </f:facet>
                    <h:outputText value="#{client.phoneNumber}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Date of birth
                    </f:facet>
                    <h:outputText value="#{client.dateOfBirth}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Type
                    </f:facet>
                    <h:outputText value="#{client.type}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        No. of inventory
                    </f:facet>
                    <h:outputText value="#{clientListBean.getNumberOfInventory(client)}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Actions
                    </f:facet>
                    <p:commandLink actionListener="#{clientListBean.removeClient(client)}" value="Delete "/>
                    <p:commandLink action="#{clientListBean.overview(client)}"
						value="Overview "></p:commandLink>
                </h:column>
            </h:dataTable>
        </h:form>

        <h:form id="actionForm">
            <h:commandButton id="addNewCustomerBtn" action="addNewCustomer" value="Add New Customer"/>
        </h:form>

   	</ui:define>
</ui:composition>

src/main/webapp/report.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets" template="template.xhtml">

	<ui:define name="page_title">
		Report
	</ui:define>
	<ui:define name="title">
		Report
	</ui:define>
	
    <ui:define name="content">
        <h:form id="tableActionForm">
            <h:dataTable value="#{reportBean.clientListByItemCount}" var="client">
                <f:facet name="header">
                        5 clients having most items
                </f:facet>
                <h:column>
                    <f:facet name="header">
                        First Name
                    </f:facet>
                    <h:outputText value="#{client.firstName}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Last Name
                    </f:facet>
                    <h:outputText value="#{client.lastName}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Phone number
                    </f:facet>
                    <h:outputText value="#{client.phoneNumber}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Date of birth
                    </f:facet>
                    <h:outputText value="#{client.dateOfBirth}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Type
                    </f:facet>
                    <h:outputText value="#{client.type}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        No. of inventory
                    </f:facet>
                    <h:outputText value="#{clientListBean.getNumberOfInventory(client)}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Actions
                    </f:facet>
                    <p:commandLink action="#{clientListBean.overview(client)}"
						value="Overview "></p:commandLink>
                </h:column>
            </h:dataTable>
            
            
            <br/>
            <br/>
            
            <h:dataTable value="#{reportBean.clientListByWeigth}" var="client">
                <f:facet name="header">
                        5 clients having most item weigth
                </f:facet>
                <h:column>
                    <f:facet name="header">
                        First Name
                    </f:facet>
                    <h:outputText value="#{client.firstName}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Last Name
                    </f:facet>
                    <h:outputText value="#{client.lastName}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Phone number
                    </f:facet>
                    <h:outputText value="#{client.phoneNumber}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Date of birth
                    </f:facet>
                    <h:outputText value="#{client.dateOfBirth}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Type
                    </f:facet>
                    <h:outputText value="#{client.type}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Weigth
                    </f:facet>
                    <h:outputText value="#{reportBean.getWeightSum(client)}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Actions
                    </f:facet>
                    <p:commandLink action="#{clientListBean.overview(client)}"
						value="Overview "></p:commandLink>
                </h:column>
            </h:dataTable>
            
            <br/>
            
        </h:form>

   	</ui:define>
</ui:composition>

src/main/webapp/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
      
	<h:head>
  		<title>
  			<ui:insert name="page_title"></ui:insert>
  		</title>
  		<h:outputStylesheet name="styles.css"/>
	</h:head>

	<h:body>

		<div class="menu">
			<h:form>
				<p:tabMenu>
					<p:menuitem value="Home" outcome="main"/>
					<p:menuitem value="Report" outcome="report"/>
				</p:tabMenu>
			</h:form>
		</div>
		
		<div class="context">
			<h2>
				<ui:insert name="title"/>
			</h2>
		</div>
	
		<div class="context">
			<ui:insert name="content"/>
		</div>
  
	</h:body>
</html>